{{- if .Values.server.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.worker" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.server.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.server.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.worker" . }}
  metrics:
  {{- if .Values.server.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.server.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.server.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.server.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{ if .Values.server.autoscaling.behavior -}}
  behavior:
    {{- toYaml .Values.server.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
