{{- if .Values.server.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.worker" . }}
  {{- if .Values.commonLabels }}
  labels:
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
  {{- end }}
spec:
  maxReplicas: {{ .Values.server.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.server.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.worker" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.server.autoscaling.targetCPUUtilizationPercentage }}
  {{ if .Values.server.autoscaling.behavior -}}
  behavior: 
    {{- toYaml .Values.server.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
