apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.jmx.exporter.enabled }}
    - port: {{ .Values.jmx.exporter.port }}
      targetPort: jmx-exporter
      protocol: TCP
      name: jmx-exporter
    {{- end }}
    {{- range $key, $value := .Values.coordinator.additionalExposedPorts }}
    - port: {{ $value.servicePort }}
      name: {{ $value.name }}
      targetPort: {{ $value.port }}
      protocol: {{ $value.protocol }}
    {{- end }}
  selector:
    {{- include "trino.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
