name: Frigate

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  frigate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Frigate
        run: pip install frigate
      - name: Check if chart README is in-sync
        run: |
          frigate gen charts/trino > charts/trino/README.md
          if ! git diff --exit-code --quiet; then
            cat << 'EOF'
          charts/trino/README.md is not in sync with chart
          Please update charts/trino/README.md by running:
              python3 -m venv .venv && . .venv/bin/activate
              pip install frigate
              frigate gen charts/trino > charts/trino/README.md
          
          Here's a diff of what's changed:
          EOF

            git diff
            # fail the job
            exit 1
          else
            echo "charts/trino/README.md is in-sync with chart"
          fi
